version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:1.34.1
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./vw-data:/data
    ports:
      - 8080:80
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      SIGNUPS_ALLOWED: false

  cloudflared:
      image: cloudflare/cloudflared:2025.6.0-amd64
      container_name: cloudflared-use-vaultwarden
      restart: unless-stopped
      command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
      volumes:
        - ./cloudflared-data:/data


