version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:1.30.5
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./vw-data:/data
    ports:
      - 8080:80
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      SIGNUPS_ALLOWED: false
      YUBICO_CLIENT_ID: ${YUBICO_CLIENT_ID}
      YUBICO_SECRET_KEY: ${YUBICO_SECRET_KEY}

  cloudflared:
      image: cloudflare/cloudflared:2024.2.1-amd64
      container_name: cloudflared-use-vaultwarden
      restart: unless-stopped
      command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
      volumes:
        - ./cloudflared-data:/data


