version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:1.25.1
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./vw-data:/data
    ports:
      - 8080:80
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
  cloudflared:
      image: cloudflare/cloudflared:2022.8.2-amd64
      container_name: cloudflared
      restart: unless-stopped
      command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
      volumes:
        - ./cloudflared-data:/data

networks:
  default:
    name: vaultwarden
#networkの意味は私よく理解できていない....
